{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a8e0b712-53e4-406c-88c7-78317144f59d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-07 01:11:00,713\tINFO util.py:154 -- Outdated packages:\n",
      "  ipywidgets==7.8.1 found, needs ipywidgets>=8\n",
      "Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\windows_events.py\", line 322, in run_forever\n",
      "    super().run_forever()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1987, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\PMLS\\AppData\\Local\\Temp\\ipykernel_92452\\3893076743.py\", line 3, in <module>\n",
      "    from sklearn.linear_model import LinearRegression\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\__init__.py\", line 84, in <module>\n",
      "    from .base import clone\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\base.py\", line 19, in <module>\n",
      "    from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py\", line 11, in <module>\n",
      "    from ._chunking import gen_batches, gen_even_slices\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_chunking.py\", line 8, in <module>\n",
      "    from ._param_validation import Interval, validate_params\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 14, in <module>\n",
      "    from .validation import _is_arraylike_not_scalar\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 26, in <module>\n",
      "    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 11, in <module>\n",
      "    from .fixes import parse_version\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py\", line 24, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 26, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.1.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(attr_name)\u001b[0m\n\u001b[0;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[0;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[0;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[0;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[0;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[1;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[0;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[1;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.1.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\windows_events.py\", line 322, in run_forever\n",
      "    super().run_forever()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1987, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\PMLS\\AppData\\Local\\Temp\\ipykernel_92452\\3893076743.py\", line 3, in <module>\n",
      "    from sklearn.linear_model import LinearRegression\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\__init__.py\", line 84, in <module>\n",
      "    from .base import clone\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\base.py\", line 19, in <module>\n",
      "    from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py\", line 11, in <module>\n",
      "    from ._chunking import gen_batches, gen_even_slices\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_chunking.py\", line 8, in <module>\n",
      "    from ._param_validation import Interval, validate_params\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 14, in <module>\n",
      "    from .validation import _is_arraylike_not_scalar\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 26, in <module>\n",
      "    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 11, in <module>\n",
      "    from .fixes import parse_version\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py\", line 24, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\core\\api.py\", line 1, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\_libs\\__init__.py\", line 17, in <module>\n",
      "    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.1.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(attr_name)\u001b[0m\n\u001b[0;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[0;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[0;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[0;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[0;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[1;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[0;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[1;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.1.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-07 01:11:02,956\tINFO worker.py:1634 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379...\n",
      "2024-12-07 01:11:02,964\tINFO worker.py:1819 -- Connected to Ray cluster.\n",
      "2024-12-07 01:11:03,106\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Fault Tolerance Test: 2 Workers with 2 Failures (over 3 trials)\n",
      "Simulated failure for task: ObjectRef(fa31b89f94899135ffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(44bfa4a5859b21acffffffffffffffffffffffff0300000001000000)\n",
      "Trial 1: No surviving workers completed their tasks.\n",
      "Simulated failure for task: ObjectRef(0ab01f2d6283d719ffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(62ffec03f52574bdffffffffffffffffffffffff0300000001000000)\n",
      "Trial 2: No surviving workers completed their tasks.\n",
      "\u001b[33m(raylet)\u001b[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: fa890c0b84666e06a67b9af31b50d715cdd372af03000000 Worker ID: 62393ea2e4891110db9dcb0d249b06a7b1c56b496655e72dead53605 Node ID: ddf46cc29f954199e1fdd9d4ca119f09663a730b83b3f48dcd7b7dc7 Worker IP address: 127.0.0.1 Worker port: 10017 Worker PID: 93208 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned. RPC Error message: Connection reset; RPC Error details: \n",
      "Simulated failure for task: ObjectRef(882ffa20ac4b2e6effffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(1d181ec2e662d748ffffffffffffffffffffffff0300000001000000)\n",
      "Trial 3: No surviving workers completed their tasks.\n",
      "Overall Average R^2 Score after failures: 0.0000\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=92908)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=92908)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=92908)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=92908)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=92908)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m Traceback (most recent call last):  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\workers\\default_worker.py\", line 289, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     worker.main_loop()\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\worker.py\", line 920, in main_loop\n",
      "\u001b[36m(pid=92908)\u001b[0m     self.core_worker.run_task_loop()\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 361, in get_execution_info\n",
      "\u001b[36m(pid=92908)\u001b[0m     self._wait_for_function(function_descriptor, job_id)\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 428, in _wait_for_function\n",
      "\u001b[36m(pid=92908)\u001b[0m     if self.fetch_and_register_remote_function(key) is True:\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "\u001b[36m(pid=92908)\u001b[0m     function = pickle.loads(serialized_function)\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\__init__.py\", line 84, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .base import clone\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\base.py\", line 19, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py\", line 11, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from ._chunking import gen_batches, gen_even_slices\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_chunking.py\", line 8, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from ._param_validation import Interval, validate_params\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 14, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .validation import _is_arraylike_not_scalar\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 26, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 11, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .fixes import parse_version\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py\", line 24, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     import pandas as pd\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 26, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from pandas.compat import (\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from pandas.compat.pyarrow import (\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     import pyarrow as pa\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     import pyarrow.lib as _lib\n",
      "\u001b[36m(pid=92908)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py\", line 44, in __getattr__\n",
      "\u001b[36m(pid=92908)\u001b[0m     raise ImportError(msg)\n",
      "\u001b[36m(pid=92908)\u001b[0m ImportError: \n",
      "\u001b[36m(pid=92908)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=92908)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=92908)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=92908)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=92908)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=92908)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=92908)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=92908)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=92908)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=92908)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=92908)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m Traceback (most recent call last):  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\workers\\default_worker.py\", line 289, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     worker.main_loop()\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\worker.py\", line 920, in main_loop\n",
      "\u001b[36m(pid=92908)\u001b[0m     self.core_worker.run_task_loop()\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 361, in get_execution_info\n",
      "\u001b[36m(pid=92908)\u001b[0m     self._wait_for_function(function_descriptor, job_id)\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 428, in _wait_for_function\n",
      "\u001b[36m(pid=92908)\u001b[0m     if self.fetch_and_register_remote_function(key) is True:\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "\u001b[36m(pid=92908)\u001b[0m     function = pickle.loads(serialized_function)\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\__init__.py\", line 84, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .base import clone\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\base.py\", line 19, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py\", line 11, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from ._chunking import gen_batches, gen_even_slices\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_chunking.py\", line 8, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from ._param_validation import Interval, validate_params\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 14, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .validation import _is_arraylike_not_scalar\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 26, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 11, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from .fixes import parse_version\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py\", line 24, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     import pandas as pd\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 49, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from pandas.core.api import (\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\core\\api.py\", line 1, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     from pandas._libs import (\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\_libs\\__init__.py\", line 17, in <module>\n",
      "\u001b[36m(pid=92908)\u001b[0m     import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]\n",
      "\u001b[36m(pid=92908)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(pid=92908)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py\", line 44, in __getattr__\n",
      "\u001b[36m(pid=92908)\u001b[0m     raise ImportError(msg)\n",
      "\u001b[36m(pid=92908)\u001b[0m ImportError: \n",
      "\u001b[36m(pid=92908)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=92908)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=92908)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=92908)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=92908)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=92908)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=92908)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "\u001b[36m(pid=91896)\u001b[0m \n",
      "2024-12-07 01:11:06,275\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2024-12-07 01:11:06,341\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Communication Overhead for 2 workers: 3.11 seconds\n",
      "\n",
      "Fault Tolerance Test: 4 Workers with 2 Failures (over 3 trials)\n",
      "Simulated failure for task: ObjectRef(bba958ebc147821cffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(d1f8fccc5d0997adffffffffffffffffffffffff0300000001000000)\n",
      "Trial 1: Average R^2 Score after failures: 0.6088, Average Training Time: 0.02 seconds\n",
      "Simulated failure for task: ObjectRef(b5ee7196461fabb2ffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(92ba3d58fa71ff60ffffffffffffffffffffffff0300000001000000)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n",
      "\u001b[36m(pid=78016)\u001b[0m \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 2: Average R^2 Score after failures: 0.6058, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(e014f98d69f9c6dcffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(8d630eb8890317ceffffffffffffffffffffffff0300000001000000)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n",
      "\u001b[36m(pid=93272)\u001b[0m \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 3: Average R^2 Score after failures: 0.6079, Average Training Time: 0.01 seconds\n",
      "Overall Average R^2 Score after failures: 0.6075\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n",
      "\u001b[36m(pid=92948)\u001b[0m \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Communication Overhead for 4 workers: 0.95 seconds\n",
      "\n",
      "Fault Tolerance Test: 8 Workers with 2 Failures (over 3 trials)\n",
      "Simulated failure for task: ObjectRef(18749ad48ef6860cffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(f1f684a908232704ffffffffffffffffffffffff0300000001000000)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=93592)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "\u001b[36m(pid=82840)\u001b[0m \n",
      "2024-12-07 01:11:10,356\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 1: Average R^2 Score after failures: 0.6087, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(020ad482d0cf4e15ffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(8f766538ab157fbbffffffffffffffffffffffff0300000001000000)\n",
      "\u001b[33m(raylet)\u001b[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 58903c2d61e0505ab420273264428ec0fb9510e803000000 Worker ID: f6dc8e98d9231c6923060d4b1691edbf0b1fe344bdc74bef4428724d Node ID: ddf46cc29f954199e1fdd9d4ca119f09663a730b83b3f48dcd7b7dc7 Worker IP address: 127.0.0.1 Worker port: 10035 Worker PID: 82840 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned. RPC Error message: Connection reset; RPC Error details: \n",
      "Trial 2: Average R^2 Score after failures: 0.6087, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(7122cba5615c347fffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(e7aa12bca1b5c70dffffffffffffffffffffffff0300000001000000)\n",
      "Trial 3: Average R^2 Score after failures: 0.6107, Average Training Time: 0.01 seconds\n",
      "Overall Average R^2 Score after failures: 0.6094\n",
      "\n",
      "Communication Overhead for 8 workers: 0.07 seconds\n",
      "\n",
      "Fault Tolerance Test: 10 Workers with 2 Failures (over 3 trials)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-07 01:11:10,626\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulated failure for task: ObjectRef(c149fead3afd6354ffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(f3758f9148a9b281ffffffffffffffffffffffff0300000001000000)\n",
      "\u001b[33m(raylet)\u001b[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 10d6766f3b09e195172c57cb366cb5134db0141f03000000 Worker ID: 481b7c1f29a303507b50e185a34c7e2954f2f566047036df467f25d0 Node ID: ddf46cc29f954199e1fdd9d4ca119f09663a730b83b3f48dcd7b7dc7 Worker IP address: 127.0.0.1 Worker port: 10033 Worker PID: 93272 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.\n",
      "Trial 1: Average R^2 Score after failures: 0.6133, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(db7066b2f85bcd5affffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(78287bbc3065ef47ffffffffffffffffffffffff0300000001000000)\n",
      "Trial 2: Average R^2 Score after failures: 0.6125, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(4734df6ace9f4391ffffffffffffffffffffffff0300000001000000)\n",
      "Simulated failure for task: ObjectRef(44af0eceb1313c56ffffffffffffffffffffffff0300000001000000)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-07 01:11:10,759\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2024-12-07 01:11:10,808\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 3: Average R^2 Score after failures: 0.6123, Average Training Time: 0.01 seconds\n",
      "Overall Average R^2 Score after failures: 0.6127\n",
      "\n",
      "Communication Overhead for 10 workers: 0.43 seconds\n",
      "\n",
      "Resource Usage:\n",
      "Total CPU Cores: 12\n",
      "Available CPU Cores: 8.0\n",
      "Total Memory: 7.73 GB\n",
      "Used Memory: 7.10 GB\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=82840)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\u001b[32m [repeated 24x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m If you are a user of the module, the easiest solution will be to\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m We expect that some modules will need time to support NumPy 2.\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m Traceback (most recent call last):  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\workers\\default_worker.py\", line 289, in <module>\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     worker.main_loop()\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\worker.py\", line 920, in main_loop\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     self.core_worker.run_task_loop()\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 361, in get_execution_info\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     self._wait_for_function(function_descriptor, job_id)\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 428, in _wait_for_function\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     if self.fetch_and_register_remote_function(key) is True:\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     function = pickle.loads(serialized_function)\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\_libs\\__init__.py\", line 17, in <module>\u001b[32m [repeated 138x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from .base import clone\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from ._chunking import gen_batches, gen_even_slices\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from ._param_validation import Interval, validate_params\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from .validation import _is_arraylike_not_scalar\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from .fixes import parse_version\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     import pandas as pd\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from pandas.compat import (\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from pandas.compat.pyarrow import (\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     import pyarrow as pa\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     import pyarrow.lib as _lib\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m Traceback (most recent call last):\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py\", line 44, in __getattr__\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     raise ImportError(msg)\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m ImportError: \u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from pandas.core.api import (\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     from pandas._libs import (\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=82840)\u001b[0m     import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]\u001b[32m [repeated 6x across cluster]\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "import ray\n",
    "import numpy as np\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.datasets import fetch_california_housing\n",
    "from sklearn.model_selection import train_test_split\n",
    "import time\n",
    "import psutil\n",
    "\n",
    "# Initialize Ray\n",
    "ray.init(ignore_reinit_error=True, dashboard_port=8265)\n",
    "\n",
    "# Load California Housing Dataset and increase the size\n",
    "def load_data():\n",
    "    data = fetch_california_housing()\n",
    "    X, y = data.data, data.target\n",
    "    \n",
    "    # Increase the size of the dataset by tripling the data\n",
    "    X = np.tile(X, (6, 1))  # Repeat the data three times (for X)\n",
    "    y = np.tile(y, 6)       # Repeat the target values three times (for y)\n",
    "    \n",
    "    return train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "# Linear regression training function\n",
    "@ray.remote\n",
    "def train_worker(X, y):\n",
    "    start_time = time.time()  # Start timer for the worker\n",
    "    model = LinearRegression()\n",
    "    model.fit(X, y)\n",
    "    score = model.score(X, y)  # R^2 score\n",
    "    training_time = time.time() - start_time  # Calculate training time for this worker\n",
    "    return score, training_time\n",
    "\n",
    "# Fault Tolerance Test with Average Calculation\n",
    "def measure_fault_tolerance(num_workers, num_failures, X_train, y_train, num_trials=5):\n",
    "    print(f\"\\nFault Tolerance Test: {num_workers} Workers with {num_failures} Failures (over {num_trials} trials)\")\n",
    "\n",
    "    trial_results = []\n",
    "\n",
    "    for trial in range(num_trials):\n",
    "        workers = []\n",
    "        split_X = np.array_split(X_train, num_workers)\n",
    "        split_y = np.array_split(y_train, num_workers)\n",
    "\n",
    "        # Launch workers\n",
    "        for i in range(num_workers):\n",
    "            workers.append(train_worker.remote(split_X[i], split_y[i]))\n",
    "\n",
    "        # Simulate failures\n",
    "        for _ in range(num_failures):\n",
    "            if workers:\n",
    "                failed_worker = workers.pop(np.random.randint(len(workers)))\n",
    "                ray.cancel(failed_worker, force=True)\n",
    "                print(f\"Simulated failure for task: {failed_worker}\")\n",
    "\n",
    "        # Collect results from surviving workers\n",
    "        results = []\n",
    "        training_times = []\n",
    "        for worker in workers:\n",
    "            try:\n",
    "                result, worker_training_time = ray.get(worker)\n",
    "                results.append(result)\n",
    "                training_times.append(worker_training_time)\n",
    "            except Exception as e:\n",
    "                print(f\"Task {worker} failed with error: {e}\")\n",
    "\n",
    "        if results:\n",
    "            avg_score = np.mean(results)\n",
    "            avg_training_time = np.mean(training_times)\n",
    "            trial_results.append(avg_score)\n",
    "            print(f\"Trial {trial + 1}: Average R^2 Score after failures: {avg_score:.4f}, Average Training Time: {avg_training_time:.2f} seconds\")\n",
    "        else:\n",
    "            print(f\"Trial {trial + 1}: No surviving workers completed their tasks.\")\n",
    "            trial_results.append(0)\n",
    "\n",
    "    # Calculate overall average fault tolerance score\n",
    "    overall_avg_score = np.mean(trial_results)\n",
    "    print(f\"Overall Average R^2 Score after failures: {overall_avg_score:.4f}\\n\")\n",
    "    return overall_avg_score\n",
    "\n",
    "# Resource monitoring function\n",
    "def monitor_resource_usage():\n",
    "    total_cores = psutil.cpu_count(logical=True)\n",
    "    available_cores = ray.available_resources().get(\"CPU\", 0)\n",
    "    total_memory = psutil.virtual_memory().total / (1024 ** 3)  # GB\n",
    "    used_memory = (total_memory - psutil.virtual_memory().available / (1024 ** 3))\n",
    "\n",
    "    print(f\"Total CPU Cores: {total_cores}\")\n",
    "    print(f\"Available CPU Cores: {available_cores}\")\n",
    "    print(f\"Total Memory: {total_memory:.2f} GB\")\n",
    "    print(f\"Used Memory: {used_memory:.2f} GB\")\n",
    "\n",
    "# Measure communication overhead\n",
    "def measure_communication_overhead(num_workers, X_train, y_train):\n",
    "    start_time = time.time()\n",
    "\n",
    "    split_X = np.array_split(X_train, num_workers)\n",
    "    split_y = np.array_split(y_train, num_workers)\n",
    "\n",
    "    # Launch workers and collect results\n",
    "    workers = [train_worker.remote(split_X[i], split_y[i]) for i in range(num_workers)]\n",
    "    ray.get(workers)\n",
    "\n",
    "    end_time = time.time()\n",
    "    communication_time = end_time - start_time\n",
    "    print(f\"Communication Overhead for {num_workers} workers: {communication_time:.2f} seconds\")\n",
    "\n",
    "# Main execution\n",
    "if __name__ == \"__main__\":\n",
    "    X_train, X_test, y_train, y_test = load_data()\n",
    "\n",
    "    # Test fault tolerance with different configurations (2, 4, 8, and 10 workers)\n",
    "    for num_workers in [2, 4, 8, 10]:\n",
    "        measure_fault_tolerance(num_workers=num_workers, num_failures=2, X_train=X_train, y_train=y_train, num_trials=3)\n",
    "\n",
    "        # Measure communication overhead\n",
    "        measure_communication_overhead(num_workers=num_workers, X_train=X_train, y_train=y_train)\n",
    "\n",
    "    # Monitor resource usage\n",
    "    print(\"\\nResource Usage:\")\n",
    "    monitor_resource_usage()\n",
    "\n",
    "    ray.shutdown()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e035dd08-3741-4478-a8d5-5111162ede40",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bcdc42c-269e-458e-b8a6-0ff38c0a56f3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
